dist: trusty
sudo: false

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk=3.0.36-1

language: ruby
cache:
  directories:
  - vendor/bundle
  - vendor/cookbooks
bundler_args: --path=$PWD/vendor/bundle
rvm:
  - 2.4.0

script:
  - chef exec cookstyle
  - chef exec foodcritic --progress -f any .

services: docker
env:
  matrix:
  # - TESTS="integration:docker[kibana4-apache-ubuntu-1404]"
  # - TESTS="integration:docker[kibana4-nginx-ubuntu-1404]"
  # - TESTS="integration:docker[kibana4-apache-package-ubuntu-1404]"
  # - TESTS="integration:docker[kibana4-apache-ubuntu-1604]"
  # - TESTS="integration:docker[kibana4-nginx-ubuntu-1604]"
  # - TESTS="integration:docker[kibana4-apache-package-ubuntu-1604]"
  # - TESTS="integration:docker[kibana4-apache-centos-69]"
  # - TESTS="integration:docker[kibana4-nginx-centos-69]"
  # - TESTS="integration:docker[kibana4-apache-centos-741708]"
  # - TESTS="integration:docker[kibana4-nginx-centos-741708]"
  - TESTS="integration:docker[kibana5-nginx-package-ubuntu-1604]"

# before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 2.4.17
# install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant development'

# script: travis_retry chef exec bundle exec rake ${TESTS}

script:
  - chef exec cookstyle
  - chef exec foodcritic --progress -f any .
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml chef exec kitchen test ${TESTS}
  - cat .kitchen/logs/kitchen.log

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
