language: ruby
rvm:
  - 2.4.0

sudo: required
services: docker

env:
  matrix:
  - TESTS="unit"
  - TESTS="rubocop"
  - TESTS="foodcritic"
  - TESTS="integration:docker[kibana4-apache-ubuntu-1404]"
  - TESTS="integration:docker[kibana4-nginx-ubuntu-1404]"
  - TESTS="integration:docker[kibana4-apache-package-ubuntu-1404]"
  - TESTS="integration:docker[kibana4-apache-ubuntu-1604]"
  - TESTS="integration:docker[kibana4-nginx-ubuntu-1604]"
  - TESTS="integration:docker[kibana4-apache-package-ubuntu-1604]"
  - TESTS="integration:docker[kibana4-apache-centos-69]"
  - TESTS="integration:docker[kibana4-nginx-centos-69]"
  - TESTS="integration:docker[kibana4-apache-centos-741708]"
  - TESTS="integration:docker[kibana4-nginx-centos-741708]"

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.3.43
install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script: travis_retry chef exec bundle exec rake ${TESTS}
