language: ruby
rvm:
  - 1.9.3
  - 2.0.0

sudo: required
services: docker

env:
  matrix:
  - TESTS="rubocop"
  - TESTS="foodcritic"
  - TESTS="integration:docker[default-ubuntu-1204]"
  - TESTS="integration:docker[default-centos-64]"

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.9.0
install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script: travis_retry chef exec bundle exec rake ${TESTS}